---
title: "Quantitative Analysis of Archaeological Data"
site: distill::distill_website
---

## Welcome!

This is a Github page setup to host lectures and other content for the University of Utah course __ANTH 5850: Quantitative Analysis of Archaeological Data__. Mostly, you'll find the lecture slides and labs for this course. You can see a link to them in the navbar. The site was built using the R package [distill](https://rstudio.github.io/distill/). The source code for this website, along with the lecture slides and lab exercises, can be found at the associated [Github repository](https://github.com/kbvernon/qaad).

## Inspiration?

I can't take credit for all of the content in this course. The lecture slides, in particular, are adapted from the lectures of [Dr. Simon Brewer](https://faculty.utah.edu/u0784726-SIMON_C._BREWER/teaching/index.hml;jsessionid=7AAABB19497C8EC501602EDB0FFEA437) in the Department of Geography at the University of Utah. The R labs, at least the parts of them concerned with data science rather than statistics, draw heavily on the very popular book [R for Data Science](https://r4ds.had.co.nz/index.html) by Hadley Wickham and Garrett Grolemund.

It probably goes without saying, of course, but those folks are way smarter than I could ever hope to be, so any errors or confusions that occur here are definitely, one-hundred percent, without a doubt my own. 


## Reuse {.appendix}

Text and figures are licensed under Creative Commons Attribution [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/). Any computer code (R, HTML, CSS, etc.) in slides and worksheets, including in slide and worksheet sources, is also licensed under [MIT](https://github.com/wilkelab/SDS375/LICENSE.md). Note that figures in slides may be pulled in from external sources and may be licensed under different terms. For such images, image credits are available in the slide notes, accessible via pressing the letter 'p'.